version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Logs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
