version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Logs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"

  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_DB: Logs
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
