"use client";
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../styles/theme'; // Adjust the import path as needed
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const innerTheme = createTheme(theme);

  return (
    <ThemeProvider theme={innerTheme}>
      <CssBaseline>
        <html lang="en">
          <head>
            {/* Ensure you have a <head> tag */}
          </head>
          <body className={inter.className}>
              <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
          </body>
        </html>
      </CssBaseline>
    </ThemeProvider>
  );
}
