name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (Repository Root)
        run: |
          cd .
          docker buildx build --platform linux/amd64,linux/arm64 -t mvlbs/log-status-page:latest --push .

      - name: Build and push Docker image (aws/lambda/log_status_ship)
        run: |
          cd aws/lambda/log_status_ship
          docker buildx build --platform linux/amd64,linux/arm64 -t mvlbs/log-status-lambda-ship:latest --push .

      - name: Build and push Docker image (aws/lambda/log_status_ship)
        run: |
            cd tasks/initialize-db
            docker buildx build --platform linux/amd64,linux/arm64 -t mvlbs/log-status-initialize-db:latest --push .
  